# my global config
global:
  scrape_interval: 15s 
  evaluation_interval: 15s 

# alertmanager configurations
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - 'localhost:9097'

rule_files:
    - "rules/alerts.yaml"


scrape_configs:
  - job_name: "prometheus"
    scheme: https
    tls_config:
      ca_file: 'public.crt'
      server_name: 'localhost' # For self signed certificates we need to add our domain/server name, If you have a valid certificate, you can skip this line.
      insecure_skip_verify: true
    basic_auth:
      username: "userprom"
      password: "grafana"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "application-server"
    static_configs:
      - targets: ["<node-ip>:9100"]
